### ISSUE TITLE
Can't install FPM or FennecDebug app on Android 5

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#25]
## Steps to reproduce
1. Install the FPM app on Android 5.1.1.

### Expected behavior
Firefox Profile Manager is installed. 

### Actual behavior
The error is displayed: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

### Device information

* Android device: Samsung Galaxy Tab A 6 (Android 5.1.1)
* Build: https://drive.google.com/file/d/1Kv3vI2uJH1bXT2peJliBI_cVcWwyGZm_/view

**Comment by Mugurell** [comment]
I think this issue stems from the apk signing method used, in the above builds v2.
https://source.android.com/security/apksigning
A new archive containing v1 signed apks can be found here - https://drive.google.com/file/d/1BXrH6zkciXpfY8vvf1bBd-oeERojjj0C/view
Please test again when you have time and confirm if the problem is resolved.

**Comment by sflorean** [comment]
This is working now with the new builds. Thank you, @Mugurell.
