### ISSUE TITLE
The backups list UI is different for imported backups

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#54]
## Preconditions:
Have backups on Firefox Profile Manager.
## Steps to reproduce
1. Launch Firefox Profile Manager;
2. Tap the Import button;
3. Select a .zip file;
4. Observe the UI for the imported backup; 
### Expected behavior
The imported backups UI is the same with the existing backups.
### Actual behavior
The imported backups UI is different.
### Notes:
[Screenshot](https://drive.google.com/file/d/1Z9-MAnqaJeTo2zMgLg2JVu_M_Y163YmH/view)
### Device information
* Android device: Samsung Galaxy S8 (Android 9); Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0).
* Build Firefox Profile Manager v1.0 Build 3 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
Because we introduce a new mime type - ".fpm" we cannot force the picker to filter for only such files.
Most we can do is just check the file selected by the user and only allow it to be imported if it has the ".fpm" name ending.
This would resolve the issue describe here and possibly others.

To help the user I propose first showing a Toast with the message
> Select a .fpm file

and if the user selected file fails the name ending check show a Toast with the following message
> This does not seem to be a FPM backup.\nCannot import.

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM builds 6 with Samsung Galaxy S8 (Android 9), Motorola Moto G6 (Android 8.0), Google Pixel 3 (Android Q), Samsung Galaxy Tab A 6 (Android 5.1.1), HTC Desire 820 (Android 6.0.1), Huawei Honor 8 (Android 7.0). 
I had opened a new issue regarding the UI for the imported backups size: https://github.com/mozilla-mobile/fennec-profile-manager/issues/75
I will close this issue. Thanks!
