### ISSUE TITLE
For more than 9 backups, the buttons "Import" and "Create" are overlapping the last entry

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#56]
## Preconditions
- Firefox Profile Manager is installed.

## Steps to reproduce
1. Open FPM. 
2. Create more than one backup (more than 9), in order for the page to be scrollable. 
3. Pay attention to the last entry.

### Expected behavior
There is no overlapping between backups and buttons.

### Actual behavior
The buttons Import and Create are overlapping the last entry.

### Device information
*Android device: Motorola Moto G6 (Android 8.0).
*Build Firefox Profile Manager v1.0 Build 3 for Fennec Release, Beta and Nightly.

![Screenshot_20191220-120021](https://user-images.githubusercontent.com/58466444/71255164-da3ea980-2335-11ea-94ba-5cb55ed9877c.png)

**Comment by andlzr** [comment]
- the floating action buttons (import and create) will now become invisible upon touch down event and visible upon touch up event in order to reveal any important information about the backup on the same Y-axis.
- same behavior is present when sliding a backup row in order to reveal actions (edit, share, delete, etc.)

**Comment by ebalazs-sv** [comment]
Verified as fixed on build Firefox Profile Manager v1.0 Build 4 for Fennec Release, Beta and Nightly with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0), Samsung Galaxy Tab A 6 (Android 5.1.1).
